name: python 3.8
dependencies:
  - numpy=1.20.2
  - pandas=1.2.4
  - pillow=8.1.2
  - scipy=1.6.3
  - rdkit=2022.3.4          #Cheminformatics
  - scikit-learn=0.24.2     #Machine learning
  - matplotlib=3.4.1        #Visualization
  - seaborn=0.11.1          #Visualization